export type ToolCategory =
  | "Downloaders"
  | "Media"
  | "PDF"
  | "Documents"
  | "Utilities";

export type ToolInput = "url" | "upload" | "text";

export type ToolOptionRow = [label: string, ...choices: string[]];

export type Tool = {
  slug: string;
  name: string;
  cat: ToolCategory;
  desc: string;
  input: ToolInput;
  emptyTitle: string;
  empty: string;
  accepts: string;
  opts: ToolOptionRow[];
  binary: boolean;
  deps: string;
};

const RAW: Array<
  [
    string,
    string,
    ToolCategory,
    string,
    ToolInput,
    string,
    string,
    string,
    ToolOptionRow[],
    boolean,
    string,
  ]
> = [
  [
    "youtube",
    "YouTube Downloader",
    "Downloaders",
    "Video, audio and subtitles from any public YouTube link",
    "url",
    "Paste a link to begin",
    "A single video, a playlist, or a channel tab.",
    "URL",
    [],
    true,
    "yt-dlp + ffmpeg",
  ],
  [
    "social",
    "Universal Social Downloader",
    "Downloaders",
    "One field, auto-detects nine platforms",
    "url",
    "One field, nine platforms",
    "Drop in a link and we work out the platform.",
    "URL",
    [],
    true,
    "yt-dlp",
  ],
  [
    "tiktok",
    "TikTok Downloader",
    "Downloaders",
    "Videos and slideshows, with or without watermark",
    "url",
    "Paste a TikTok link",
    "Video posts and photo slideshows. Watermark removal is best-effort.",
    "URL",
    [
      ["Output", "MP4 · no watermark", "MP4 · original", "MP3 audio"],
      ["Cover image", "Save", "Skip"],
    ],
    true,
    "yt-dlp",
  ],
  [
    "instagram",
    "Instagram Downloader",
    "Downloaders",
    "Reels, posts and carousels",
    "url",
    "Paste a Reel or post link",
    "Public posts only. Carousels download as a numbered set.",
    "URL",
    [
      ["Output", "MP4", "JPG set", "MP3 audio"],
      ["Caption", "Save as .txt", "Skip"],
    ],
    true,
    "yt-dlp",
  ],
  [
    "facebook",
    "Facebook Downloader",
    "Downloaders",
    "Public videos and reels",
    "url",
    "Paste a Facebook video link",
    "Public videos only — private and group posts need a cookies file.",
    "URL",
    [["Quality", "Best", "720p", "360p"]],
    true,
    "yt-dlp",
  ],
  [
    "x",
    "X / Twitter Downloader",
    "Downloaders",
    "Video and GIF posts",
    "url",
    "Paste a post link",
    "Works with video and animated GIF posts.",
    "URL",
    [["Output", "MP4", "GIF", "Audio"]],
    true,
    "yt-dlp",
  ],
  [
    "reddit",
    "Reddit Downloader",
    "Downloaders",
    "Merges Reddit's split video and audio streams",
    "url",
    "Paste a Reddit post link",
    "Reddit hosts video and audio separately — we merge them for you.",
    "URL",
    [["Audio", "Merge", "Video only"]],
    true,
    "yt-dlp + ffmpeg",
  ],
  [
    "vimeo",
    "Vimeo Downloader",
    "Downloaders",
    "Public and unlisted Vimeo videos",
    "url",
    "Paste a Vimeo link",
    "Password-protected videos need the password below.",
    "URL",
    [
      ["Quality", "Best", "1080p", "720p"],
      ["Password", "Not required", "Enter…"],
    ],
    true,
    "yt-dlp",
  ],
  [
    "twitch",
    "Twitch Clips & VODs",
    "Downloaders",
    "Clips, highlights and full VODs",
    "url",
    "Paste a clip or VOD link",
    "Long VODs download in segments and are stitched at the end.",
    "URL",
    [
      ["Source", "Clip", "VOD", "Highlight"],
      ["Chat log", "Include .json", "Skip"],
    ],
    true,
    "yt-dlp",
  ],
  [
    "soundcloud",
    "SoundCloud Downloader",
    "Downloaders",
    "Tracks, sets and playlists with tags",
    "url",
    "Paste a track or set link",
    "Metadata and cover art are written into the file.",
    "URL",
    [
      ["Format", "MP3 320", "M4A", "Opus"],
      ["Artwork", "Embed", "Save separately"],
    ],
    true,
    "yt-dlp",
  ],
  [
    "video-convert",
    "Video Convert",
    "Media",
    "MOV, MKV, WebM and AVI into clean MP4",
    "upload",
    "Drop a video to convert",
    "MOV, MKV, WebM, AVI, MP4, FLV. Batch up to 10 files.",
    "MOV · MKV · WEBM · AVI",
    [],
    true,
    "ffmpeg",
  ],
  [
    "audio-convert",
    "Audio Convert",
    "Media",
    "WAV, FLAC and M4A to MP3, Opus or AAC",
    "upload",
    "Drop audio files",
    "Lossless in, compressed out — tags are carried over.",
    "WAV · FLAC · M4A · MP3",
    [
      ["Target", "MP3 320", "Opus 128", "AAC 256", "FLAC"],
      ["Normalize", "Off", "EBU R128"],
    ],
    true,
    "ffmpeg",
  ],
  [
    "compress-video",
    "Compress Video",
    "Media",
    "Hit a target size without wrecking quality",
    "upload",
    "Drop a video to compress",
    "We two-pass encode to land within 2% of your target.",
    "MP4 · MOV · MKV",
    [
      ["Mode", "Target size", "Quality slider"],
      ["Target", "25 MB", "100 MB", "500 MB"],
    ],
    true,
    "ffmpeg",
  ],
  [
    "extract-audio",
    "Extract Audio",
    "Media",
    "Pull the soundtrack out of any video",
    "upload",
    "Drop a video",
    "The audio stream is copied when possible — no re-encode, no loss.",
    "MP4 · MKV · MOV · WEBM",
    [
      ["Format", "MP3", "M4A", "WAV"],
      ["Channels", "Stereo", "Mono"],
    ],
    true,
    "ffmpeg",
  ],
  [
    "trim",
    "Trim / Clip",
    "Media",
    "Cut a range with frame-accurate handles",
    "upload",
    "Drop a video to trim",
    "Scrub the timeline, set in and out, export just that range.",
    "MP4 · MOV · MKV",
    [["Cut mode", "Fast (keyframe)", "Precise (re-encode)"]],
    true,
    "ffmpeg",
  ],
  [
    "gif",
    "GIF Maker",
    "Media",
    "Turn a clip range into a tuned GIF",
    "upload",
    "Drop a video to make a GIF",
    "Pick a range under 15 seconds for a sensible file size.",
    "MP4 · MOV · WEBM",
    [
      ["Frame rate", "12 fps", "15 fps", "24 fps"],
      ["Width", "320", "480", "640"],
      ["Palette", "Optimised", "Grayscale"],
    ],
    true,
    "ffmpeg",
  ],
  [
    "mute",
    "Mute / Strip Audio",
    "Media",
    "Remove audio tracks, keep the video untouched",
    "upload",
    "Drop a video to mute",
    "Stream copy — the video is never re-encoded.",
    "MP4 · MOV · MKV",
    [["Tracks", "Strip all", "Keep track 1"]],
    true,
    "ffmpeg",
  ],
  [
    "resfps",
    "Resolution / FPS",
    "Media",
    "Rescale and retime video",
    "upload",
    "Drop a video to rescale",
    "Downscaling looks better than upscaling — we will warn you either way.",
    "MP4 · MOV · MKV",
    [
      ["Resolution", "2160p", "1080p", "720p", "480p"],
      ["Frame rate", "Keep", "60", "30", "24"],
    ],
    true,
    "ffmpeg",
  ],
  [
    "image-convert",
    "Image Convert",
    "Media",
    "PNG, JPG, WebP and AVIF, in any direction",
    "upload",
    "Drop images to convert",
    "Up to 100 images at once. Transparency is preserved where the target allows.",
    "PNG · JPG · WEBP · AVIF",
    [
      ["Target format", "WebP", "PNG", "JPG", "AVIF"],
      ["Quality", "75", "60", "90", "Lossless"],
    ],
    false,
    "imagescript",
  ],
  [
    "image-resize",
    "Image Resize / Compress",
    "Media",
    "Resize, crop and squeeze image weight",
    "upload",
    "Drop images to resize",
    "Set a long-edge cap and a quality target; we do the rest.",
    "PNG · JPG · WEBP",
    [
      ["Long edge", "1200", "800", "1600", "2400"],
      ["Quality", "Balanced", "High", "Small", "Lossless"],
    ],
    false,
    "imagescript",
  ],
  [
    "pdf-merge",
    "Merge PDF",
    "PDF",
    "Combine files into one, in your order",
    "upload",
    "Drop PDFs to merge",
    "Two or more files. Drag to set the order before merging.",
    "PDF",
    [],
    false,
    "pdf-lib",
  ],
  [
    "pdf-split",
    "Split PDF",
    "PDF",
    "Extract page ranges into new files",
    "upload",
    "Drop a PDF to split",
    "Use ranges like 1-3, 7, 12-end.",
    "PDF",
    [
      ["Mode", "Every page", "Ranges", "Every N pages"],
      ["Chunk size", "2", "5", "10"],
      ["Output", "One ZIP", "Separate files"],
    ],
    false,
    "pdf-lib",
  ],
  [
    "pdf-compress",
    "Compress PDF",
    "PDF",
    "Shrink scans and image-heavy documents",
    "upload",
    "Drop a PDF to compress",
    "Text stays sharp; embedded images are re-sampled.",
    "PDF",
    [["Preset", "Screen 96dpi", "eBook 150dpi", "Print 300dpi"]],
    true,
    "ghostscript",
  ],
  [
    "pdf-images",
    "PDF ↔ Images",
    "PDF",
    "Pages out to PNG, or images in to PDF",
    "upload",
    "Drop a PDF or a set of images",
    "Direction is detected from what you drop.",
    "PDF · PNG · JPG",
    [
      ["Direction", "PDF → PNG", "Images → PDF"],
      ["DPI", "72", "150", "300"],
    ],
    true,
    "pdftoppm",
  ],
  [
    "pdf-rotate",
    "Rotate / Reorder Pages",
    "PDF",
    "Fix orientation and page order",
    "upload",
    "Drop a PDF to rearrange",
    "Thumbnails appear here — drag to reorder, click to rotate.",
    "PDF",
    [
      ["Rotate", "90° CW", "90° CCW", "180°"],
      ["Apply to", "All pages", "Selected"],
    ],
    false,
    "pdf-lib",
  ],
  [
    "pdf-watermark",
    "Watermark PDF",
    "PDF",
    "Stamp text or an image across pages",
    "upload",
    "Drop a PDF to watermark",
    "Text or a transparent PNG, placed on every page or a range.",
    "PDF",
    [
      ["Type", "Text", "Image"],
      ["Position", "Diagonal", "Centre", "Footer"],
      ["Opacity", "10%", "25%", "50%"],
    ],
    false,
    "pdf-lib",
  ],
  [
    "pdf-protect",
    "Protect / Unlock PDF",
    "PDF",
    "Add or remove a password",
    "upload",
    "Drop a PDF",
    "We never store passwords — they live in memory for the length of the job.",
    "PDF",
    [
      ["Action", "Protect", "Unlock"],
      ["Permissions", "No printing", "No copying", "Full"],
    ],
    true,
    "qpdf",
  ],
  [
    "docx-pdf",
    "DOCX → PDF",
    "Documents",
    "Word documents with layout intact",
    "upload",
    "Drop a .docx file",
    "Fonts are embedded; track changes are flattened.",
    "DOCX · DOC",
    [
      ["Page size", "A4", "Letter"],
      ["Comments", "Hide", "Show"],
    ],
    true,
    "libreoffice",
  ],
  [
    "pdf-docx",
    "PDF → DOCX",
    "Documents",
    "Best-effort conversion back to editable Word",
    "upload",
    "Drop a PDF to convert",
    "Honest note: complex layouts, columns and scanned pages will need cleanup.",
    "PDF",
    [
      ["Layout", "Keep visual", "Flow text"],
      ["Images", "Embed", "Drop"],
    ],
    true,
    "libreoffice",
  ],
  [
    "markdown",
    "Markdown ↔ PDF/DOCX",
    "Documents",
    "Render Markdown into paged documents",
    "upload",
    "Drop or paste Markdown",
    "GFM tables, code blocks and footnotes are supported.",
    "MD · MARKDOWN",
    [
      ["Target", "PDF", "DOCX", "HTML"],
      ["Theme", "Plain", "Technical", "Manuscript"],
    ],
    true,
    "pandoc",
  ],
  [
    "txt-pdf",
    "TXT / RTF → PDF",
    "Documents",
    "Plain text into a typeset page",
    "upload",
    "Drop a .txt or .rtf file",
    "Line breaks are preserved; long lines wrap to the page.",
    "TXT · RTF",
    [
      ["Font", "Serif", "Sans", "Mono"],
      ["Size", "10pt", "12pt", "14pt"],
    ],
    false,
    "pandoc",
  ],
  [
    "images-pdf",
    "Images → PDF",
    "Documents",
    "Bundle images into a paged PDF",
    "upload",
    "Drop images",
    "Order the pages, choose a fit, export one PDF.",
    "PNG · JPG · HEIC",
    [
      ["Fit", "Fill page", "Fit with margin"],
      ["Orientation", "Auto", "Portrait", "Landscape"],
    ],
    false,
    "pdf-lib",
  ],
  [
    "qr",
    "QR Generate / Decode",
    "Utilities",
    "Make QR codes or read one from an image",
    "text",
    "",
    "",
    "",
    [],
    false,
    "",
  ],
  [
    "hash",
    "Hash / Checksum",
    "Utilities",
    "MD5, SHA-1, SHA-256 for text or files",
    "upload",
    "Drop a file or paste text",
    "Compare against an expected checksum to verify a download.",
    "ANY FILE",
    [
      ["Algorithm", "MD5", "SHA-1", "SHA-256", "SHA-512"],
      ["Case", "lower", "UPPER"],
    ],
    false,
    "",
  ],
  [
    "base64",
    "Base64 Encode / Decode",
    "Utilities",
    "Text and files, both directions",
    "text",
    "",
    "Paste text or drop a file. Data-URI wrapping optional.",
    "TEXT · ANY FILE",
    [
      ["Direction", "Encode", "Decode"],
      ["Wrap", "None", "Data URI", "76 cols"],
    ],
    false,
    "",
  ],
  [
    "jsonyaml",
    "JSON / YAML Formatter",
    "Utilities",
    "Format, minify and convert between them",
    "text",
    "",
    "Paste a document — errors are highlighted with line numbers.",
    "JSON · YAML",
    [
      ["Action", "Format", "Minify", "JSON → YAML", "YAML → JSON"],
      ["Indent", "2", "4", "Tab"],
    ],
    false,
    "",
  ],
  [
    "regex",
    "Regex Tester",
    "Utilities",
    "Live matches, groups and replace preview",
    "text",
    "",
    "Write a pattern and test text; matches highlight as you type.",
    "TEXT",
    [
      ["Flags", "g", "i", "m", "s"],
      ["Mode", "Match", "Replace", "Split"],
    ],
    false,
    "",
  ],
  [
    "metadata",
    "Metadata Strip",
    "Utilities",
    "Remove EXIF, GPS and media tags",
    "upload",
    "Drop files to clean",
    "We show you what will be removed before anything is written.",
    "JPG · PNG · MP4 · PDF",
    [["Remove", "All metadata", "GPS only", "Keep copyright"]],
    false,
    "exiftool",
  ],
];

export const TOOLS: Tool[] = RAW.map(
  ([slug, name, cat, desc, input, emptyTitle, empty, accepts, opts, binary, deps]) => ({
    slug,
    name,
    cat,
    desc,
    input,
    emptyTitle,
    empty,
    accepts,
    opts,
    binary,
    deps: deps || "runtime",
  }),
);

export const TOOL_CATEGORIES = [
  "All",
  "Downloaders",
  "Media",
  "PDF",
  "Documents",
  "Utilities",
] as const;

export const FEATURED_SLUGS = [
  "youtube",
  "video-convert",
  "pdf-merge",
  "image-convert",
] as const;

export const HIFI_SLUGS = new Set([
  "youtube",
  "social",
  "video-convert",
  "pdf-merge",
  "image-convert",
  "qr",
]);

export function getTool(slug: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function countByCategory(cat: ToolCategory): number {
  return TOOLS.filter((t) => t.cat === cat).length;
}

export function categoryFlags(cat: ToolCategory) {
  return {
    isDL: cat === "Downloaders",
    isMD: cat === "Media",
    isPD: cat === "PDF",
    isDC: cat === "Documents",
    isUT: cat === "Utilities",
  };
}
